const invoiceFormFields = {
  top: [
    {
      label: 'Company',
      id: 'company',
      required: true,
      row: 1,
      width: 6,
    },
    {
      label: 'Client',
      id: 'client',
      required: true,
      width: 6,
      row: 1,
    },
    {
      label: 'Service Type',
      id: 'serviceType',
      required: true,
      width: 4,
      row: 2,
    },
    {
      label: 'Invoice Number',
      id: 'invoiceNumber',
      required: true,
      width: 4,
      row: 2,
    },
    {
      label: 'Invoice Type',
      id: 'invoiceType',
      required: true,
      width: 4,
      row: 2,
    },
    {
      label: 'Payment Method',
      id: 'paymentMethod',
      required: true,
      row: 3,
      width: 6,
    },
    {
      label: 'Date',
      id: 'date',
      required: true,
      row: 3,
      width: 6,
      fieldType: 'datetime-local',
    },
    {
      label: 'Payment deadline',
      id: 'paymentDeadline',
      required: true,
      row: 4,
      width: 6,
      fieldType: 'date',
    },
    {
      label: 'Shipment date',
      id: 'shipmentDate',
      required: true,
      row: 4,
      width: 6,
      fieldType: 'date',
    },
    {
      label: 'Notes',
      id: 'notes',
      required: false,
      row: 5,
      width: 12,
      fieldType: 'textarea',
    },
  ],
  bottom: [
    {
      label: 'Currency',
      id: 'currency',
      required: true,
      row: 1,
      width: 4,
      fieldType: 'select',
    },
  ],
}
export const invoiceFormFieldsBottom = [
  {
    label: 'Currency',
    id: 'currency',
    required: true,
    row: 6,
    width: 4,
    fieldType: 'select',
  },
]
export const invoiceItemsFields = [
  {
    label: 'Description',
    id: 'description',
    required: true,
    row: 1,
    width: 12,
    fieldType: 'textarea',
  },
  {
    label: 'Unit',
    id: 'unit',
    required: true,
    row: 2,
    width: 2,
    fieldType: 'text',
  },
  {
    label: 'Price',
    id: 'price',
    required: true,
    row: 2,
    width: 3,
    fieldType: 'number',
  },
  {
    label: 'Amount',
    id: 'amount',
    required: true,
    row: 2,
    width: 2,
    fieldType: 'number',
  },
  {
    label: 'Discount',
    id: 'discount',
    required: false,
    row: 2,
    width: 2,
    fieldType: 'number',
  },
  {
    label: 'Tax',
    id: 'tax',
    required: false,
    row: 2,
    width: 3,
    fieldType: 'number',
  },
]
export default invoiceFormFields
